In [32]:
import numpy as np
import sys

In [ ]:
#provando que o numpy é melhor que a lista normal

In [2]:
a = [1,2,3,4]
b= np.array([1,2,3,4])

In [3]:
print(a)
print(b)

[1, 2, 3, 4]
[1 2 3 4]


In [7]:
sys.getsizeof(a)

120

In [8]:
b.nbytes

16

In [9]:
#Criando listas pelo Numpy

In [10]:
#Array 1D

d1 = np.array([1,2,3])
print (d1)

[1 2 3]


In [11]:
d1.shape

(3,)

In [12]:
d1.ndim

1

In [13]:
d1.dtype

dtype('int32')

In [16]:
#Array 2D

d2 = np.array([[1,2,3], [4,5,6]])
print (d2)

[[1 2 3]
 [4 5 6]]


In [17]:
d2.shape

(2, 3)

In [18]:
d2.ndim

2

In [20]:
d2.dtype

dtype('int32')

In [24]:
#Array 3D

d3 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print (d3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
d3.shape

(2, 2, 2)

In [26]:
d3.ndim

3

In [27]:
d3.dtype

dtype('int32')

In [28]:
#comandos usando numpy

In [37]:
a = [2,3,4]
b = [2,3,4]

result = a + b
print(result)

[2, 3, 4, 2, 3, 4]


In [36]:
a = np.array([2,3,4])
b = np.array([2,3,4])

result = np.add(a, b)
print(result)

[4 6 8]


In [38]:
a = np.array([[2,3,4,5], [6,7,8,9]])
print(a)

[[2 3 4 5]
 [6 7 8 9]]


In [41]:
# Array[Row,Colu]
a[1,2]

8

In [42]:
a[0, :]

array([2, 3, 4, 5])

In [43]:
a[:, 1]

array([3, 7])

In [53]:
a[1,3]

9